### ISSUE TITLE
'No Value Present' Error on Nightly Publish

### ISSUE THREAD

**Issue by stanbrub** [deephaven/benchmark#321]
The nightly run failed on publishing the Scores tables to slack with the following message:

```
Exception in thread "main" java.lang.RuntimeException: Failed to get snapshot of table: platform_details
	at io.deephaven.benchmark.api.BenchQuery.lambda$execute$1(BenchQuery.java:75)
	at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:945)
	at io.deephaven.benchmark.api.BenchQuery.execute(BenchQuery.java:68)
	at io.deephaven.benchmark.run.PublishNotification.publish(PublishNotification.java:71)
	at io.deephaven.benchmark.run.BenchmarkMain.publish(BenchmarkMain.java:58)
	at io.deephaven.benchmark.run.BenchmarkMain.main1(BenchmarkMain.java:34)
	at io.deephaven.benchmark.run.BenchmarkMain.main(BenchmarkMain.java:28)
Caused by: java.lang.RuntimeException: Failed to fetch snapshot table data: platform_details
	at io.deephaven.benchmark.connect.BarrageConnector.lambda$fetchSnapshotData$0(BarrageConnector.java:127)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at io.deephaven.benchmark.connect.BarrageConnector.fetchSnapshotData(BarrageConnector.java:114)
	at io.deephaven.benchmark.api.BenchQuery.lambda$execute$1(BenchQuery.java:70)
	... 6 more
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at io.deephaven.benchmark.connect.BarrageConnector.findTable(BarrageConnector.java:205)
	at io.deephaven.benchmark.connect.BarrageConnector.lambda$fetchSnapshotData$0(BarrageConnector.java:119)
	... 9 more

```

**Comment by stanbrub** [comment]
The issue is that when the bean data was removed from metrics collection, the CSV reader auto-detected a type of 'int' instead of the 'double' type it detected from the previous set of metric values.  So when merging multiple runs into one table, the type definitions where seen as incompatible.
